FROM amazoncorretto:21-alpine-jdk

ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG USERNAME
ARG PASSWORD
ARG JWT_SECRET_KEY
ARG JWT_TOKEN_PREFIX
ARG JWT_TOKEN_EXPIRATION_AFTER_DAYS
ARG JWT_REFRESH_TOKEN_EXPIRATION_AFTER_DAYS
ARG JUNO_API_KEY
ARG JUNO_API_KEY_SECRET
ARG CAPA_API_KEY

ENV DB_URL=$DB_URL
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV USERNAME=$USERNAME
ENV PASSWORD=$PASSWORD
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV JWT_TOKEN_PREFIX=$JWT_TOKEN_PREFIX
ENV JWT_TOKEN_EXPIRATION_AFTER_DAYS=$JWT_TOKEN_EXPIRATION_AFTER_DAYS
ENV JWT_REFRESH_TOKEN_EXPIRATION_AFTER_DAYS=$JWT_REFRESH_TOKEN_EXPIRATION_AFTER_DAYS
ENV JUNO_API_KEY=$JUNO_API_KEY
ENV JUNO_API_KEY_SECRET=$JUNO_API_KEY_SECRET
ENV CAPA_API_KEY=$CAPA_API_KEY

EXPOSE 8080

ADD target/cb-flow-connect-api.jar cb-flow-connect-api.jar
ENTRYPOINT ["java", "-jar", "cb-flow-connect-api.jar"]